### ISSUE TITLE
Problem building the platform locally

### ISSUE THREAD

**Issue by gmer16** [OsiriX-Foundation/kheopsDocker#3]
Hi, 

I'm trying to build the platform locally using the default configuration in the ci-test branch.
Later on I plan to replace the Keycloak instance used here with a custom one running on my server.

Unfortunately I find that the system doesn't work as expected. 
When I run  `script_run_docker.sh` the `kheopsreverseproxy` container exits with this error: `2020/04/27 10:26:06 [emerg] 16#16: invalid port in upstream "localhost:8042:8042" in /etc/nginx/conf.d/kheops.conf:207 nginx: [emerg] invalid port in upstream "localhost:8042:8042" in /etc/nginx/conf.d/kheops.conf:207`,
and the `kheopsui` container exits with this other error: ``Missing KHEOPS_UI_CLIENTID environment variable``.

If I rename the `KHEOPS_UI_KEYCLOAK_CLIENTID` variable to `KHEOPS_UI_CLIENTID` and change the `KHEOPS_ROOT_URL` to `http://localhost` the system still doesn't work,
it allows me to register but there is some problem with the OIDC redirect url, it sends me to a `404 not Found` page.

Am I doing something wrong?

Thanks

**Comment by spalte** [comment]
Hello,

The ci-test branch is meant to be used for our integration testing. While it used to be the best starting point when bringing up a new instance, I have finally put up a bit of documentation and a script to help install KHEOPS. You can find it [here](https://docs.kheops.online/docs/installation).

Please let me know if you run into any trouble with it, or if you have any other comments.

**Comment by gmer16** [comment]
Hi,

Thank you very much for preparing this excellent information. I tested the script after the latest fix, but there seems to be still some problem. The `kheopsauthorization` container exits at startup, apparently because it fails to connect to the database. See the logs below:

`28-Apr-2020 09:48:06.955 INFO [main] com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger.log Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@160efa5b [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@1ac6e9c1 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgfcata91hbp3rijwpcw2|70a8ebfc, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@3fbcb217 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgfcata91hbp3rijwpcw2|29e10870, jdbcUrl -> jdbc:postgresql://kheopspostgres:5432/kheops, properties -> {password=******, user=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgfcata91hbp3rijwpcw2|5f016147, numHelperThreads -> 3 ]
28-Apr-2020 09:48:37.340 WARNING [C3P0PooledConnectionPoolManager[identityToken->1hgfcata91hbp3rijwpcw2|5f016147]-HelperThread-#0] com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$WarnLogger.log com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@16cf49a4 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
	org.postgresql.util.PSQLException: FATAL: password authentication failed for user "kheopsuser"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
		at org.postgresql.Driver.makeConnection(Driver.java:458)
		at org.postgresql.Driver.connect(Driver.java:260)
		at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
		at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
		at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
		at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
28-Apr-2020 09:48:37.342 WARNING [C3P0PooledConnectionPoolManager[identityToken->1hgfcata91hbp3rijwpcw2|5f016147]-HelperThread-#0] com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$WarnLogger.log Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3c176ee is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
28-Apr-2020 09:48:37.349 SEVERE [main] online.kheops.auth_server.liquibase.LiquibaseContextListener.contextInitialized Unable to use liquibase
	java.sql.SQLException: Connections could not be acquired from the underlying database!
		at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
		at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
		at org.hibernate.c3p0.internal.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:72)
		at online.kheops.auth_server.liquibase.LiquibaseContextListener.contextInitialized(LiquibaseContextListener.java:57)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4690)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5151)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
	Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
		at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1469)
		at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
		at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)`

I separately tried to log into the `kheopspostgres` container to see if the access credentials were wrong, but instead I was able to log in without any problem.

Thanks

**Comment by gmer16** [comment]
I solved the problem above simply restarting the system:
`docker-compose down -v; docker-compose up -d`
Now everything seems to work fine. Thanks
